#!/bin/bash
# 차수거래 학습 카드 — 시간당 자동 추가 + RL 갭 보충
set -euo pipefail
BOARD="${BOARD_ROOT:-/home/ubuntu/coupax-homepage/board}"
PY="${BOARD}/.venv/bin/python"
[ -x "$PY" ] || PY="python3"
LOG_DIR="/home/ubuntu/coupax-homepage/logs"
mkdir -p "$LOG_DIR"
HOURLY="${KIWOM_CARDS_HOURLY:-4}"
SLEEP="${KIWOM_CARDS_SLEEP_SEC:-3}"
RL_MAX="${KIWOM_RL_MAX_ADD:-2}"
TRAIN_LINE="10 * * * * cd $BOARD && PYTHONPATH=scripts $PY scripts/kiwoom_card_rl_engine.py train >> $LOG_DIR/kiwoom_rl_train.log 2>&1"
ADD_LINE="15 * * * * cd $BOARD && PYTHONPATH=scripts $PY scripts/kiwoom_auto_add_cards.py --hourly $HOURLY --sleep $SLEEP --rl >> $LOG_DIR/kiwoom_auto_cards.log 2>&1"
WIKI_LINE="20 * * * * cd $BOARD && PYTHONPATH=scripts $PY scripts/sync_kiwoom_wiki.py >> $LOG_DIR/kiwoom_wiki_sync.log 2>&1"
COUNCIL_LINE="25 * * * * cd $BOARD && PYTHONPATH=scripts KIWOM_CARD_COUNCIL_ENABLED=1 $PY scripts/kiwoom_card_council.py create --max 1 >> $LOG_DIR/kiwoom_card_council.log 2>&1"
MONITOR_LINE="*/15 * * * * cd $BOARD && PYTHONPATH=scripts WONHERO_MONITOR_ENABLED=1 $PY scripts/wonhero_trade_monitor.py run >> $LOG_DIR/wonhero_trade_monitor.log 2>&1"
MAINTAIN_LINE="5 * * * * cd $BOARD && PYTHONPATH=scripts $PY scripts/wonhero_catalog_maintain.py run >> $LOG_DIR/wonhero_catalog_maintain.log 2>&1"
WORKER_LINE="*/15 * * * * cd $BOARD && PYTHONPATH=scripts AGENT_OFFICE_WORKER_ENABLED=1 $PY scripts/agent_office_worker.py >> $LOG_DIR/agent_office_worker.log 2>&1"
( crontab -l 2>/dev/null | grep -v "kiwoom_auto_add_cards.py" | grep -v "sync_kiwoom_wiki.py" | grep -v "kiwoom_card_rl_engine.py" | grep -v "kiwoom_card_council.py" | grep -v "wonhero_trade_monitor.py" | grep -v "wonhero_catalog_maintain.py" | grep -v "agent_office_worker.py" || true
  echo "$TRAIN_LINE"
  echo "$ADD_LINE"
  echo "$WIKI_LINE"
  echo "$COUNCIL_LINE"
  echo "$MONITOR_LINE"
  echo "$MAINTAIN_LINE"
  echo "$WORKER_LINE"
) | crontab -
echo "installed: $TRAIN_LINE"
echo "installed: $ADD_LINE"
echo "installed: $WIKI_LINE"
echo "installed: $COUNCIL_LINE"
echo "installed: $MONITOR_LINE"
echo "installed: $MAINTAIN_LINE"
echo "installed: $WORKER_LINE"
